"""initial_schema

Revision ID: 0c4fb4a8376c
Revises: 
Create Date: 2026-04-19 09:11:08.975103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4fb4a8376c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alpaca_tokens_user_id_key', 'alpaca_tokens', type_='unique')
    op.create_index(op.f('ix_alpaca_tokens_id'), 'alpaca_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_alpaca_tokens_user_id'), 'alpaca_tokens', ['user_id'], unique=True)
    op.create_index(op.f('ix_kyc_submissions_status'), 'kyc_submissions', ['status'], unique=False)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_kyc_submissions_status'), table_name='kyc_submissions')
    op.drop_index(op.f('ix_alpaca_tokens_user_id'), table_name='alpaca_tokens')
    op.drop_index(op.f('ix_alpaca_tokens_id'), table_name='alpaca_tokens')
    op.create_unique_constraint('alpaca_tokens_user_id_key', 'alpaca_tokens', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
